2020-05-28T01:04:25.2898125+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T01:04:25.3005908+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T01:04:25.3032814+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T09:44:10.6648552+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T09:44:10.6861173+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T09:44:10.6908297+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T09:46:36.1072152+06:00 80000012-0003-f300-b63f-84710c7967bb [INF] New Applicant created (1015b257)
2020-05-28T09:46:37.1837200+06:00 80000012-0003-f300-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T09:46:58.0892124+06:00 80000010-0001-f500-b63f-84710c7967bb [INF] New Applicant created (1015b257)
2020-05-28T09:48:47.7171789+06:00 80000010-0001-f500-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T09:49:59.3967377+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T09:49:59.4074281+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T09:49:59.4095702+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T09:50:54.2126657+06:00 8000002a-0000-ec00-b63f-84710c7967bb [INF] New Applicant created (1015b257)
2020-05-28T09:50:58.1529121+06:00 8000002a-0000-ec00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T09:51:54.7103862+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T09:51:54.7377179+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T09:51:54.7423002+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T09:53:09.9718862+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T09:53:09.9826338+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T09:53:09.9844527+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T10:03:53.3027674+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T10:03:53.3164741+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T10:03:53.3222006+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T10:04:32.9677823+06:00 80000008-0002-fe00-b63f-84710c7967bb [INF] New Applicant created (1015b257)
2020-05-28T10:04:36.2213079+06:00 80000008-0002-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtRouteResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T10:10:29.3826540+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T10:10:29.4679175+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T10:10:29.4741702+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T10:11:01.0656331+06:00 80000012-0002-fe00-b63f-84710c7967bb [INF] New Applicant created (1015b257)
2020-05-28T10:12:34.0383634+06:00 8000000c-0003-fe00-b63f-84710c7967bb [INF] Applicant updated successfully (a09c6c18)
2020-05-28T10:53:30.9395272+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T10:53:30.9668110+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T10:53:30.9792138+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T10:55:01.3004756+06:00 80000004-0000-fa00-b63f-84710c7967bb [ERR] Unable to get country list from given Api. An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set. (81b66e70)
2020-05-28T10:55:01.7219622+06:00 80000004-0000-fa00-b63f-84710c7967bb [ERR] An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set. (165785d6)
2020-05-28T10:59:27.1873955+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T10:59:27.2998838+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T10:59:27.3257111+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T11:01:28.5439889+06:00 80000028-0002-fe00-b63f-84710c7967bb [ERR] Country of origin - string is not a valid country. Please provide a valid one (be50cd74)
2020-05-28T11:01:58.1267525+06:00 8000000b-0000-fd00-b63f-84710c7967bb [ERR] Country of origin - bANGLADESH is not a valid country. Please provide a valid one (77ff642d)
2020-05-28T11:03:18.6966036+06:00 8000002a-0002-fe00-b63f-84710c7967bb [ERR] Country of origin - bangladesh is not a valid country. Please provide a valid one (e9ee4eae)
2020-05-28T11:08:12.0337247+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T11:08:12.1225195+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T11:08:12.2230599+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T11:09:11.5506363+06:00 80000013-0000-fd00-b63f-84710c7967bb [INF] New Applicant created (1015b257)
2020-05-28T11:09:50.1032176+06:00 80000036-0002-fe00-b63f-84710c7967bb [INF] New Applicant created (1015b257)
2020-05-28T14:37:45.6834235+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T14:37:45.6974161+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T14:37:45.6999799+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T14:37:45.8902177+06:00 80000002-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:37:46.2481119+06:00 80000004-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:38:09.1706443+06:00 80000002-0001-ff00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:38:09.2628584+06:00 80000006-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:38:26.7283699+06:00 80000008-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:38:26.8138877+06:00 80000002-0002-f900-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:40:08.6632812+06:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-28T14:40:08.6711143+06:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-28T14:40:08.6730667+06:00  [INF] Content root path: "E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web" (b5d60022)
2020-05-28T14:40:08.7512445+06:00 8000000a-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:40:08.9917351+06:00 8000000c-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:41:24.9846935+06:00 80000002-0003-ff00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-28T14:41:25.0776121+06:00 80000005-0001-ff00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.))
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\kibria\Visual Studio Default Path\Job Test\HHHH\Hahn.ApplicatonProcess.Application - Copy\Hahn.ApplicatonProcess.May2020.Web\aurelia-app\aurelia_project\aurelia.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.FindTcpPortAsync(String sourcePath)
   at Aurelia.DotNet.AureliaCliDevelopmentServer.StartCreateAureliaCliAppServerAsync(String sourcePath, String nodeScriptName, ILogger logger, PackageManager packageManager, Boolean hotModuleReload)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aurelia.DotNet.AureliaCliDevelopmentServer.<>c.<Attach>b__4_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
